# Generated by Django 6.0.2 on 2026-02-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_rename_activity_subtask_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='course_name',
            field=models.CharField(default='blank-course', max_length=200),
            preserve_default=False,
        ),
    ]
