# Generated by Django 6.0.2 on 2026-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_activity_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the subject', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subject was created')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['-creation_date'],
            },
        ),
    ]
