# Generated by Django 6.0.2 on 2026-03-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Linked academic subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='planner.subject'),
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='planner.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subject',
                'verbose_name_plural': 'User Subjects',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
