# Generated by Django 5.2.7 on 2026-03-13 15:19

from django.db import migrations, models


def _backfill_unique_user_emails(apps, schema_editor):
    User = apps.get_model("planner", "User")
    used_emails = set()

    for user in User.objects.order_by("id"):
        current_email = (user.email or "").strip().lower()
        needs_update = current_email != (user.email or "")

        if not current_email or current_email in used_emails:
            base_local = (user.username or f"user{user.id}").strip().lower() or f"user{user.id}"
            candidate = f"{base_local}+{user.id}@placeholder.local"
            i = 1
            while candidate in used_emails:
                candidate = f"{base_local}+{user.id}-{i}@placeholder.local"
                i += 1
            current_email = candidate
            needs_update = True

        used_emails.add(current_email)

        if needs_update:
            user.email = current_email
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(_backfill_unique_user_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
