# Generated by Django 6.0.2 on 2026-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'due_date'], name='planner_act_user_id_e63223_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'status'], name='planner_act_user_id_ea5360_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['user', 'affected_date', 'status'], name='planner_con_user_id_92c402_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-creation_date'], name='planner_sub_creatio_2d1363_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='planner_sub_name_3715f4_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['target_date', 'status'], name='planner_sub_target__e62387_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['activity_id', 'status'], name='planner_sub_activit_efd9bf_idx'),
        ),
    ]
