# Generated by Django 6.0.2 on 2026-05-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_activity_planner_act_user_id_e63223_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_tour', models.BooleanField(default=False)),
                ('has_seen_org_tour', models.BooleanField(default=False)),
                ('has_seen_progress_tour', models.BooleanField(default=False)),
                ('has_seen_conflict_tour', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_user',
            },
        ),
    ]
