# Generated by Django 6.0.2 on 2026-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_useronboarding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['activity_id', 'target_date', 'status'], name='planner_sub_activit_30ea32_idx'),
        ),
    ]
