name: Build container image

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "server/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-backend-image:
    name: Build backend container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build backend image
        working-directory: server
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vida_academica-backend

          docker build \
            -t ${IMAGE_ID}:${{ github.sha }} \
            -t ${IMAGE_ID}:latest \
            .

      - name: Push backend image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vida_academica-backend

          docker push ${IMAGE_ID}:${{ github.sha }}
          docker push ${IMAGE_ID}:latest

  build-frontend-image:
    name: Build frontend container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build frontend image
        working-directory: client
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vida_academica-frontend

          docker build \
            -t ${IMAGE_ID}:${{ github.sha }} \
            -t ${IMAGE_ID}:latest \
            .

      - name: Push frontend image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vida_academica-frontend

          docker push ${IMAGE_ID}:${{ github.sha }}
          docker push ${IMAGE_ID}:latest
